version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3002:3002
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    container_name: postgre_container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: loan
      POSTGRES_DB: loan 