version: '3.9'
services:
  postgre_container:
    restart: always
    image: postgres:latest
    container_name: postgre_container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: loan
      POSTGRES_DB: loan 

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  mysqldata:
    driver: local

  